remote: origin
target-branch: main
chart-dirs:
  - helm
helm-extra-args: "--timeout 600s"
validate-chart-schema: true
validate-chart-values: true
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
