---
{{- include "bjw-s.common.loader.init" . }}

{{- define "boobielicious.hardcodedValues" -}}

# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

initContainers:
  wait-for-db:
    name: wait-for-db
    image: ghcr.io/patrickdappollonio/wait-for:latest
    command:
      - /wait-for
    args:
      - --host="{{ .Release.Name }}-postgresql:5432"
      - --host="{{ .Release.Name }}-redis:6379"
      - --timeout=60s
      - --verbose

env:
  DATABASE_URL: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  NZBGET_DOWNLOAD_PATH: /downloads
  REDIS_HOST: "{{ .Release.Name }}-redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: {{ .Values.redis.auth.password }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "boobielicious.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
