image:
  # -- image repository
  repository: ghcr.io/boobielicious/boobielicious
  # -- image tag
  # tag: ""
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Environment variables.
env:
  # -- NZBGet download category
  NZBGET_CATEGORY: stash
  # -- NZBGet JSON-RPC URL
  NZBGET_JSONRPC_API: http://nzbget:6789/jsonrpc
  # -- NZBGet user
  NZBGET_USERNAME: ""
  # -- NZBGet password
  NZBGET_PASSWORD: ""
  # -- NZBHydra2 API endpoint
  NZBHYDRA_ENDPOINT: http://nzbhydra2:5076
  # -- NZBHydra2 API key
  NZBHYDRA_API_KEY: ""
  # -- Dropzone folder for performers
  PERFORMER_DROPZONE_FOLDER: _dropzone
  # -- Stash GraphQL API endpoint
  STASH_GRAPHQL_API: http://stash:9999/graphql
  # -- Stash image host protocol
  STASH_IMAGE_REMOTE_PROTOCOL: https
  # -- Stash image hostname
  STASH_IMAGE_REMOTE_HOSTNAME: stash
  # -- Stash image host port
  STASH_IMAGE_REMOTE_PORT: "9999"
  # -- Twitter Access Token
  TWITTER_BEARER_TOKEN: ""

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    # -- Configure the Service port information here.
    ports:
      http:
        # -- The port number
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    # -- Enables or disables the ingress
    enabled: false
    ## Configure the hosts for the ingress
    hosts:
      - # -- Host address. Helm template can be passed.
        host: chart-example.local
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  downloads:
    enabled: false
    existingClaim: nfs-downloads
    subPath:
      - mountPath: /downloads
        path: completed/stash
  performers:
    enabled: false
    existingClaim: nfs-stash
    subPath:
      - mountPath: /performers
        path: performers

cronjobs:
  cleanupDownloads:
    # -- Enables cleaning up downloads
    enabled: false
    # -- Schedule time in UTC
    schedule: "* * * * *"
    # -- How many pods to keep around for successful jobs
    successfulJobsHistoryLimit: 1
    # -- How many pods to keep around for failed jobs
    failedJobsHistoryLimit: 1
    # -- How to treat failed jobs
    restartPolicy: Never
    podAnnotations: {}

  cleanupSortedVideos:
    # -- Enables cleaning up sorted videos
    enabled: false
    # -- Schedule time in UTC
    schedule: "0 5 * * *"
    # -- How many pods to keep around for successful jobs
    successfulJobsHistoryLimit: 1
    # -- How many pods to keep around for failed jobs
    failedJobsHistoryLimit: 1
    # -- How to treat failed jobs
    restartPolicy: Never
    podAnnotations: {}

  updateStatus:
    # -- Enables updating status of newznab items
    enabled: false
    # -- Schedule time in UTC
    schedule: "* * * * *"
    # -- How many pods to keep around for successful jobs
    successfulJobsHistoryLimit: 1
    # -- How many pods to keep around for failed jobs
    failedJobsHistoryLimit: 1
    # -- How to treat failed jobs
    restartPolicy: Never
    podAnnotations: {}

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: boobielicious
    password: boobielicious
    database: boobielicious
  primary:
    persistence:
      enabled: false
      #storageClass: nfs-data

# -- Enable and configure redis database subchart under this key.
#    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
# @default -- See values.yaml
redis:
  enabled: true
  auth:
    password: boobielicious
  master:
    persistence:
      enabled: false
      #storageClass: nfs-data
  replica:
    replicaCount: 0