image:
  # -- image repository
  repository: ghcr.io/boobielicious/boobielicious
  # -- image tag
  tag: 1.2.0
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Environment variables.
env:
  # -- Stash GraphQL API endpoint
  STASH_GRAPHQL_API: https://stash/graphql
  # -- Stash image host protocol
  STASH_IMAGE_REMOTE_PROTOCOL: https
  # -- Stash image hostname
  STASH_IMAGE_REMOTE_HOSTNAME: stash
  # -- Stash image host port
  STASH_IMAGE_REMOTE_PORT: "9999"
  # -- Twitter Access Token
  TWITTER_BEARER_TOKEN: ""
  # -- Sharp path
  NEXT_SHARP_PATH: /tmp/node_modules/sharp

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    # -- Configure the Service port information here.
    ports:
      http:
        # -- The port number
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    # -- Enables or disables the ingress
    enabled: false
    ## Configure the hosts for the ingress
    hosts:
      - # -- Host address. Helm template can be passed.
        host: chart-example.local
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local