name: Release
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Build
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 'lts/*'
      - uses: volta-cli/action@v3
      - name: Install dependencies
        run: npm ci --prefer-offline
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
