---
name: Release
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   issues: write
    #   pull-requests: write
    steps:
      - name: Checkout & Build
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 'lts/*'
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - name: Add repositories
        run: |
          for dir in $(ls -d helm/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done
      - name: Build dependencies
        run: |
          for dir in $(ls -d helm/); do
            helm dependency build $dir 2> /dev/null
          done
      - uses: volta-cli/action@v4
      - name: Install dependencies
        run: npm ci --prefer-offline
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
